hostname *
copy .vimrc

hostname mob
env KITTY_SSH_SETUP=done
copy .bashrc
copy .vimrc
# uncomment to update nvim config on server
# copy .config/nvim
# copy .local/share/nvim/lazy
# copy .local/share/nvim/mason/packages/elp-25-07-21
share_connections no

hostname teamserver
env KITTY_SSH_SETUP=done
copy --dest .bashrc.user .bashrc
copy .vimrc
share_connections no

# prevent copying any config to the shared-user broccoli VDI
hostname broccoli seliiuvd06590*
# copy .config/nvim
share_connections no
